In [1]:
import numpy as np
import pandas as pd

#### np version

In [2]:
np.__version__

'1.21.5'

#### Retrieve data

In [3]:
!python -m wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv


Saved under data (1).csv


#### Read data

In [4]:
df = pd.read_csv("data.csv")

In [5]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

#### Explore data

In [6]:
df.shape

(11914, 16)

In [7]:
df["Make"].value_counts()[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

In [8]:
df[df["Make"]=='Audi']['Model'].nunique()

34

In [9]:
df.columns


Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [10]:
df.isnull().any().sum()

5

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

#### Find the median value of "Engine Cylinders" column in the dataset.

In [12]:
df['Engine Cylinders'].median()

6.0

#### calculate the most frequent value of the same "Engine Cylinders".

In [13]:
df['Engine Cylinders'].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [14]:
df['Engine Cylinders'].isna().sum()

30

#### Use fillna method to fill the missing values in "Engine Cylinders" with 4.0

In [15]:
df['Engine Cylinders'].isnull().sum()

30

In [16]:
df['Engine Cylinders'].fillna(4.0, inplace=True)

In [17]:
df['Engine Cylinders'].isnull().sum()

0

In [18]:
df['Engine Cylinders'].value_counts()

4.0     4782
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [19]:
df['Engine Cylinders'].median()

6.0

#### select all lotus cars from the dataset

In [20]:
df[df['Make']=='Lotus'].shape

(29, 16)

In [21]:
lotus_cars = df[df['Make']=='Lotus']

#### select only two columns specified below

In [22]:
new_data =lotus_cars.loc[:, ["Engine HP","Engine Cylinders"]]

In [23]:
new_data.duplicated().sum()

20

#### drop duplicates

In [24]:
new_data_no_duplicates = new_data.drop_duplicates()

#### covert to numpy array

In [43]:
X = new_data_no_duplicates.to_numpy()

In [44]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [82]:
X.shape

(9, 2)

#### Get the Transpose of the matrix

In [45]:
XT = X.T

In [46]:
XT

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

#### Matrix : Vector to Vector multiplication

In [47]:
def vector_to_vector_multiplication(u, v):
    assert u.shape[0] == u.shape[0] # check if number of rows in U is equal to number of rows in V
    
    num_rows = u.shape[0] # get the number of rows
    result = 0.0
    
    for i in range(num_rows): # loop over the number of rows and perform summation of the multiplication of elements
        result += u[i] * v[i]
    
    return result

#### Matrix : Matrix to Vector multiplication

In [48]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0] # check if number of columns in U is equal to number of rows in V
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows): # loop over the number of rows and fill in each element with vector to vector multiplication of elements
        result[i] = vector_to_vector_multiplication(U[i], v)
    
    return result

#### Matrix : Matrix to Matrix multiplication

In [49]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [50]:
XTX = matrix_matrix_multiplication(XT, X)

In [51]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

#### Using numpy dot product

In [52]:
XT.dot(X)

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

#### Invert XTX

In [83]:
XTX_inv = np.linalg.inv(XTX)

In [84]:
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

#### Create new array

In [75]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [76]:
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

#### Multiply XTX by XT

In [85]:
new_array = XTX_inv.dot(XT)

In [86]:
new_array

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

#### Multiply identity matrix by y(another array)

In [87]:
w = new_array.dot(y)

In [88]:
w[0]

4.594944810094576